BUILD=python setup.py build
INSTALL_LIB=python setup.py install_lib
INSTALL_SCR=python setup.py install_scripts
RM=rm -f
LIBEXT=so
SWIG=swig -python

ifeq ($(ARCH),mingw32)
	BUILD += -cmingw32
	RM=del /q
	LIBEXT=pyd
endif
